### ISSUE TITLE
{김민경} 백엔드 7주차 배포 세션 과제 제출입니다.

### ISSUE THREAD

**Issue by kyoooooong** [likelion-Inha-12/kyoooooong#11]
① 배포 성공한 화면
![배포최종완료](https://github.com/likelion-Inha-12/kyoooooong/assets/149250433/b72a1364-a68b-403f-9883-f30d62baa08e)

② 배포할 때 사용한 인스턴스 정보가 담긴 화면
![인스턴스](https://github.com/likelion-Inha-12/kyoooooong/assets/149250433/e9737941-91a7-431b-99f5-331afc530ada)

감사합니다 :)

**Comment by juwon0403** [comment]
혼자 해내다니 대단해..!!
고생했슴당~~

**Comment by kyoooooong** [comment]
피드백 고마워 주원 오늘 세션도 정말 짱이었습니당 😳👍
