### ISSUE TITLE
{김민경} 백엔드 8주차 https 세션 과제 제출입니다.

### ISSUE THREAD

**Issue by kyoooooong** [likelion-Inha-12/kyoooooong#13]
1. 키워드 과제

https://velog.io/@kyoooooong/%EB%A9%8B%EC%82%AC-https-%EC%84%B8%EC%85%98-%EA%B3%BC%EC%A0%9C

2.
![image](https://github.com/likelion-Inha-12/kyoooooong/assets/149250433/b8cea291-decd-4fb8-9cdb-05f8653fb04e)

**Comment by juwon0403** [comment]
작은 부분까지 아주 꼼꼼하게 과제 작성을 해주셨군용 ㅎㅎ
완벽한 과제로 임명합니다b

히히 과제하느라 수고많았어~~

**Comment by kyoooooong** [comment]
이게 다 완벽한 세션 덕분,,,🤭💛 피드백 고마와용 👍
